version: "3.8"
services:

  front:
    build:
      context: ./frontend
    depends_on:
      - back
    ports:
      - "3000:80"

  back:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: mvn spring-boot:run

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: flowmodoro