spring.application.name=flowmodoro

# Configuração do banco
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/flowmodoro}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Supabase OAuth2 / JWT Resource Server
supabase.jwt.issuer-uri=${SUPABASE_JWT_ISSUER_URI:https://localhost:8000/auth/v1}
supabase.jwt.jwks-uri=${SUPABASE_JWKS_URI:https://localhost:8000/auth/v1/.well-known/jwks.json}

